# Generated by Django 5.1.6 on 2025-04-01 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('users', '0002_user_reset_token_user_reset_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college',
        ),
        migrations.AddField(
            model_name='collegeregister',
            name='college',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='department.college'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='college',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='department.college'),
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='department.college'),
        ),
    ]
