# Generated by Django 5.1.6 on 2025-04-02 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
        ("users", "0003_remove_user_college_collegeregister_college_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collegeregister",
            name="college",
        ),
        migrations.RemoveField(
            model_name="lecturer",
            name="college",
        ),
        migrations.RemoveField(
            model_name="student",
            name="college",
        ),
        migrations.RemoveField(
            model_name="user",
            name="reset_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="reset_token_expiry",
        ),
        migrations.AddField(
            model_name="user",
            name="college",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="department.college",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="department.school",
            ),
        ),
    ]
