# Generated by Django 5.1.6 on 2025-03-15 06:24

import cloudinary.models
import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0003_rename_department_name_department_department_name"),
        ("users", "0003_alter_user_college_collegeregister_lecturer"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_domain",
        ),
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="department.department",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[users.models.validate_email_domain],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("register", "College Register"),
                    ("lecturer", "Lecturer"),
                ],
                default="student",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="collegeregister",
            name="college",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.college",
            ),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="college",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.college",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="college",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.college",
            ),
        ),
    ]
