# Generated by Django 5.1.6 on 2025-04-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_college_collegeregister_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='is_lecturer',
            field=models.BooleanField(default=True),
        ),
    ]
