# Generated by Django 5.1.6 on 2025-03-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_college_remove_user_email_domain_student_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecturer",
            name="college",
        ),
        migrations.RemoveField(
            model_name="collegeregister",
            name="college",
        ),
        migrations.RemoveField(
            model_name="user",
            name="college",
        ),
        migrations.DeleteModel(
            name="College",
        ),
    ]
