# Generated by Django 5.1.6 on 2025-03-19 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0004_college_remove_department_department_name_and_more"),
        ("users", "0005_remove_lecturer_college_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="department.college",
            ),
        ),
    ]
