# Generated by Django 5.1.6 on 2025-04-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_lecturer_is_lecturer'),
        ('users', '0005_collegeregister_college_lecturer_college_and_more'),
    ]

    operations = [
    ]
