# Generated by Django 5.1.7 on 2025-03-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_college'),
        ('users', '0007_remove_student_department_and_more'),
    ]

    operations = [
    ]
