# Generated by Django 5.1.6 on 2025-03-28 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_merge_20250322_0622"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="collegeregister",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mak_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("registrar", "Registrar"),
                    ("lecturer", "Lecturer"),
                ],
                default="student",
                max_length=25,
            ),
        ),
    ]
