# Generated by Django 5.1.6 on 2025-04-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('registrar', 'Registrar'), ('lecturer', 'Lecturer')], max_length=25, null=True),
        ),
    ]
