# Generated by Django 5.1.7 on 2025-04-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20250403_1515'),
        ('users', '0010_alter_user_mak_email'),
    ]

    operations = [
    ]
