# Generated by Django 5.1.6 on 2025-03-28 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("department", "0004_college_remove_department_department_name_and_more"),
        ("users", "0011_remove_user_full_name_remove_user_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="Male",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="collegeregister",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="register",
                to="department.department",
            ),
        ),
        migrations.AlterField(
            model_name="collegeregister",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lecturer",
                to="department.department",
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecturer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                related_name="custom_user_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="custom_user_permissions", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("registrar", "Registrar"),
                    ("lecturer", "Lecturer"),
                ],
                default="student",
                max_length=25,
            ),
        ),
    ]
