# Generated by Django 5.1.6 on 2025-03-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_collegeregister_user_alter_user_mak_email_and_more"),
        ("users", "0012_user_full_name_user_gender_and_more"),
    ]

    operations = []
