# Generated by Django 5.1.6 on 2025-03-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_merge_20250328_2007"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
