# Generated by Django 5.1.5 on 2025-02-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='gender',
            field=models.CharField(default='other', max_length=20),
        ),
    ]
