# Generated by Django 5.1.6 on 2025-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.CharField(max_length=100, verbose_name='Department')),
                ('description', models.TextField(verbose_name='Department Description')),
            ],
        ),
    ]
