# Generated by Django 5.1.5 on 2025-03-30 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cees', 'College of Education and External Studies (CEES)'), ('cocis', 'College of Computing and Information Sciences (COCIS)'), ('cedat', 'College of Engineering, Design, Art and Technology (CEDAT)'), ('chs', 'College of Health Sciences (CHS)'), ('chuss', 'College of Humanities and Social Sciences (CHUSS)'), ('conas', 'College of Natural Sciences (CONAS)'), ('caes', 'College of Agricultural and Environmental Sciences (CAES)'), ('cobams', 'College of Business and Management Sciences (COBAMS)'), ('covab', 'College of Veterinary Medicine, Animal Resources and Biosecurity (COVAB)')], default='', max_length=100, unique=True)),
                ('code', models.CharField(default='COCIS', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='', max_length=255)),
                ('college', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='department.college')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Department', max_length=100, unique=True)),
                ('description', models.TextField(verbose_name='Department Description')),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='department.school')),
            ],
        ),
    ]
