# Generated by Django 5.1.5 on 2025-03-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Department_name',
            field=models.CharField(choices=[('cees', 'CEES'), ('cocis', 'COCIS'), ('cedat', 'CEDAT'), ('chs', 'CHS'), ('chuss', 'CHUSS'), ('conas', 'CONAS'), ('caes', 'CAES'), ('cobams', 'COBAMS'), ('covab', 'COVAB'), ('school of law', 'SCHOOL OF LAW')], max_length=100, verbose_name='Department'),
        ),
    ]
