# Generated by Django 5.1.5 on 2025-03-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Department_name',
            new_name='department_name',
        ),
    ]
