# Generated by Django 5.1.6 on 2025-03-17 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0003_rename_department_name_department_department_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            (
                                "cees",
                                "College of Education and External Studies (CEES)",
                            ),
                            (
                                "cocis",
                                "College of Computing and Information Sciences (COCIS)",
                            ),
                            (
                                "cedat",
                                "College of Engineering, Design, Art and Technology (CEDAT)",
                            ),
                            ("chs", "College of Health Sciences (CHS)"),
                            (
                                "chuss",
                                "College of Humanities and Social Sciences (CHUSS)",
                            ),
                            ("conas", "College of Natural Sciences (CONAS)"),
                            (
                                "caes",
                                "College of Agricultural and Environmental Sciences (CAES)",
                            ),
                            (
                                "cobams",
                                "College of Business and Management Sciences (COBAMS)",
                            ),
                            (
                                "covab",
                                "College of Veterinary Medicine, Animal Resources and Biosecurity (COVAB)",
                            ),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(default="COCIS", max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="department",
            name="department_name",
        ),
        migrations.AddField(
            model_name="department",
            name="name",
            field=models.CharField(
                default="Unnamed Department", max_length=100, unique=True
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="college",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="department.college",
            ),
        ),
    ]
