# Generated by Django 5.1.6 on 2025-03-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_college_remove_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(default='COCIS', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(choices=[('cees', 'College of Education and External Studies (CEES)'), ('cocis', 'College of Computing and Information Sciences (COCIS)'), ('cedat', 'College of Engineering, Design, Art and Technology (CEDAT)'), ('chs', 'College of Health Sciences (CHS)'), ('chuss', 'College of Humanities and Social Sciences (CHUSS)'), ('conas', 'College of Natural Sciences (CONAS)'), ('caes', 'College of Agricultural and Environmental Sciences (CAES)'), ('cobams', 'College of Business and Management Sciences (COBAMS)'), ('covab', 'College of Veterinary Medicine, Animal Resources and Biosecurity (COVAB)')], default='', max_length=100, unique=True),
        ),
    ]
