# Generated by Django 5.1.6 on 2025-04-01 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_initial'),
        ('users', '0002_user_reset_token_user_reset_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='assigned_lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='users.lecturer'),
        ),
    ]
