# Generated by Django 5.1.6 on 2025-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issues_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='title',
            field=models.CharField(default='untitled issue', max_length=255),
        ),
        migrations.AlterField(
            model_name='issues',
            name='assigned_lecturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
