# Generated by Django 5.1.6 on 2025-04-02 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('issues', '0003_issues_assigned_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='department.department'),
        ),
        migrations.AddField(
            model_name='issues',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='department.school'),
        ),
    ]
