# Generated by Django 5.1.5 on 2025-03-11 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_rename_department_name_department_department_name'),
        ('issues', '0003_issues_title_alter_issues_assigned_lecturer'),
        ('users', '0003_alter_user_college_collegeregister_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='users.student'),
        ),
        migrations.AddField(
            model_name='issues',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='department', to='department.department'),
        ),
        migrations.AddField(
            model_name='issues',
            name='lecturer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='users.lecturer'),
        ),
        migrations.AddField(
            model_name='issues',
            name='register',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='register', to='users.collegeregister'),
        ),
    ]
