# Generated by Django 5.1.6 on 2025-03-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0004_college_remove_department_department_name_and_more"),
        ("issues", "0004_issues_author_issues_department_issues_lecturer_and_more"),
        ("users", "0006_user_college"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issues",
            name="department",
        ),
        migrations.RemoveField(
            model_name="issues",
            name="lecturer",
        ),
        migrations.AddField(
            model_name="issues",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="department.college",
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="assigned_lecturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_issues",
                to="users.lecturer",
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="attachment",
            field=models.ImageField(
                blank=True, null=True, upload_to="issue_attachments/"
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_issues",
                to="users.student",
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="register",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_issues",
                to="users.collegeregister",
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
