# Generated by Django 5.1.6 on 2025-03-28 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_college_code_alter_college_name'),
        ('issues', '0004_issues_author_issues_department_issues_lecturer_and_more'),
        ('users', '0009_alter_collegeregister_user_alter_user_mak_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='category',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='department',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='email',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='issues',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='department.college'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='assigned_lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='users.lecturer'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='issue_attachments/'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_issues', to='users.student'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='users.collegeregister'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='issues',
            name='title',
            field=models.CharField(default='Untitled Issue', max_length=255),
        ),
    ]
