# Generated by Django 5.1.6 on 2025-04-04 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('issues', '0004_issues_department_issues_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='department.college'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='department.department'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='department.school'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20),
        ),
    ]
