# Generated by Django 5.1.6 on 2025-04-19 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_alter_issues_college_alter_issues_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="issue_attachments/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
    ]
