# Generated by Django 5.1.6 on 2025-03-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_remove_issues_category_remove_issues_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='title',
            field=models.CharField(choices=[('registration_issue', 'REGISTRATION ISSUE'), ('marks_correction', 'MARKS CORRECTION')], default='marks_correction', max_length=255),
        ),
    ]
