# Generated by Django 5.1.6 on 2025-04-21 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_alter_issues_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="issues",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("missing_marks", "Missing Marks"),
                    ("appeals", "Appeals"),
                    ("correction", "Correction"),
                ],
                help_text="Issue category (e.g., Missing Marks, Appeals)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issues",
            name="course_code",
            field=models.CharField(
                blank=True,
                help_text="Format: [Department Prefix][Space][4 digits] (e.g., CSC 1201)",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Course code must be: 3-4 capital letters + space + 4 digits (e.g., "MATH 2200").',
                        regex="^[A-Z]{3,4}\\s\\d{4}$",
                    )
                ],
            ),
        ),
    ]
