# Generated by Django 5.1.5 on 2025-02-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_reg_no', models.CharField(max_length=20, unique=True)),
                ('student_no', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('year_of_study', models.IntegerField()),
                ('gender', models.CharField(default='other', max_length=20)),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
